### ISSUE TITLE
gym.error.NameNotFound: Environment Foraging-2s-10x10-4p-2f doesn't exist.

### ISSUE THREAD

**Issue by issuey** [mansicer/MAIC#10] opened 2023-07-14 03:27 UTC
Hello, I have installed the Python environment according to the requirements.txt file, but when I run the following command:
python src/main.py --config=qmix --env-config=foraging

The following error occurred
![image](https://github.com/mansicer/MAIC/assets/74280544/0a1d9aab-a5d2-4679-92a6-6561c6f90fd9)
How can I solve this mistake? is there any other environment to install?
Looking forward to your reply.

**Comment by mansicer** [comment] 2023-07-14 03:56
Hi. Sorry that I did not succeed to reproduce your errors. I think this should be some version issues from `gym`. 

Have you installed the `SMAC` package under the `qplex_smac` folder as suggested in the readme file? We archive the lb-foraging package for this repo.

```bash
pip install qplex_smac/
```

If you meet some error like `AttributeError: attempted to get missing private attribute '_valid_actions'`, you may need to install a legacy version of gym like `gym==0.16.0`, which works for me. I will lock requirements to this version in the next commit. Thanks for your question!

**Comment by issuey** [comment] 2023-07-14 06:28
> Hi. Sorry that I did not succeed to reproduce your errors. I think this should be some version issues from `gym`.
> 
> Have you installed the `SMAC` package under the `qplex_smac` folder as suggested in the readme file? We archive the lb-foraging package for this repo.
> 
> ```shell
> pip install qplex_smac/
> ```
> 
> If you meet some error like `AttributeError: attempted to get missing private attribute '_valid_actions'`, you may need to install a legacy version of gym like `gym==0.16.0`, which works for me. I will lock requirements to this version in the next commit. Thanks for your question!

Hello, thank you very much. I can train now after I modified the gym version. I want to know whether the training scene of lbforaging can be rendered, and how should I set it up?

**Comment by issuey** [comment] 2023-07-14 06:58
Thank you very much. I modified the gym version and was able to run it successfully.

**Comment by mansicer** [comment] 2023-07-17 13:08
I will close this issue as there is no more question. Feel free to reopen it if there are other problems.

**Closed as completed by mansicer** 2023-07-17 13:08 UTC
